### ISSUE TITLE
Saving current bingo sheet progress to browsers local storage

### ISSUE THREAD

**Issue by laszlostark** [Toriality/DYOM-Bingo#16]
Hello there,
I had a couple situations in the past few days where I was doing DYOM-Bingo and accidentally went back on the page, reloaded, closed the browser or at one point even the power went out lol.
Now in all of these cases the process on the bingo sheet is completely gone when loading the page again. I've seen that in the 1.4 branch there is functionality present that retains a representation of previous bingo sheets. I'd imagine this is probably done via local storage as well and especially with the implementation of seeds in 1.4 this might be a good time to introduce a feature to pick up on previous games and maybe even try to archive them in some way so that they may be titled and viewed again at wish.
At the moment I'm a little short on capacity but maybe in the coming weeks I'll try to familiarize myself with the code in the hopes of contributing, since I've just worked on a somewhat similar project myself. In the mean time consider this some kind of feature request or inspiration.
Thanks for reading and I hope you have a good day :)

**Comment by Toriality** [comment]
Hello, thanks for your suggestion. I've implemented a code for your issue on #21, you might wanna check and test locally to see if that fits your suggestion.

Feel free to request changes and provide feedback on the PR topic.
