### ISSUE TITLE
[BUG] Incorrect link given on Share button

### ISSUE THREAD

**Issue by Toriality** [Toriality/DYOM-Bingo#33]
**Describe the bug**
The Share button gives the user a incorrect URL

**To Reproduce**
1. [Go to DYOM Bingo website](https://toriality.github.io/DYOM-Bingo/)
2. Click on "Share" on the bottom of the Bingo card table
3. The site will automatically insert a URL into your clipboard, but it is an incorrect URL

**Expected behavior**
The Share button should give you the site link with the ?seed= query parameter followed by the seed string. It should be something like this:

```
https://toriality.github.io/DYOM-Bingo?seed=some_string_here
```

Instead, we're getting

```
https://toriality.github.io?seed=some_string_here
```

**Comment by logan-14** [comment]
Just opened a pull request
Just a small change in seed.js from .location to .href
